name: garmin-sync-coros

on:
  workflow_dispatch:
env:
  GITHUB_NAME: zfw
  GITHUB_EMAIL: zfwzelda@gmail.com
  ## 佳明配置
  GARMIN_AUTH_DOMAIN: ${{ secrets.GARMIN_AUTH_DOMAIN }}
  GARMIN_EMAIL: ${{ secrets.GARMIN_EMAIL }}
  GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
  GARMIN_START_TIME: ${{ secrets.GARMIN_START_TIME }}

  ## Coros配置
  COROS_EMAIL: ${{ secrets.COROS_EMAIL }}
  COROS_PASSWORD: ${{ secrets.COROS_PASSWORD }}
  COROS_START_TIME: ${{ secrets.COROS_START_TIME }}

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      # from pdm
      - name: Set Variables
        id: set_variables
        run: |
          echo "PY=$(python -c 'import hashlib, sys;print(hashlib.sha256(sys.version.encode()+sys.executable.encode()).hexdigest())')" >> $GITHUB_OUTPUT
          echo "PIP_CACHE=$(pip cache dir)" >> $GITHUB_OUTPUT
      - name: Cache PIP
        uses: actions/cache@v4
        with:
          path: ${{ steps.set_variables.outputs.PIP_CACHE }}
          key: Ubuntu-pip-${{ steps.set_variables.outputs.PY }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        if: steps.pip-cache.outputs.cache-hit != 'true'
      - name: Run Garmin or Coros Sync
        run: |
          python scripts/garmin-sync-coros.py GARMIN
      - name: Push new cookie
        run: |
          git config --local user.email "${{ env.GITHUB_EMAIL }}"
          git config --local user.name "${{ env.GITHUB_NAME }}"
          git add .
          git commit -m 'update garmin activity' || echo "nothing to commit"
          git push || echo "nothing to push"
